# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1

# Computer-generated files and other files which cannot be copyrighted
[[annotations]]
path = [
    ".ansible-lint",
    ".github/renovate.json",
    ".github/workflows/pre-commit.yml",
    ".gitignore",
    ".pre-commit-config.yaml",
    ".yamllint.yml",
    "meta/main.yml"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
